In [197]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd 
import numpy as np

model = load_model('model.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender= pickle.load(file)
    
with open('One_hot_encoder_geo.pkl','rb') as file:
    One_hot_encoder_geo= pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler= pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [198]:
input_data={
    "RowNumber": 1250,
    "CustomerId": 15738492,
    "Surname": "Smith",
    "CreditScore": 742,
    "Geography": "Germany",
    "Gender": "Male",
    "Age": 35,
    "Tenure": 6,
    "Balance": 125430.75,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 87342.56,
    "Exited": 0
}

In [199]:
input_data_df = pd.DataFrame([input_data])
y = input_data_df['Exited']
input_data_df = input_data_df.drop(columns=[ 'RowNumber','CustomerId','Surname','Exited'])

In [200]:
input_data_df['Geography']

0    Germany
Name: Geography, dtype: str

In [201]:
encoder_geo = One_hot_encoder_geo.transform(input_data_df[['Geography']].astype(str))
encoded_df = pd.DataFrame(encoder_geo,columns=One_hot_encoder_geo.get_feature_names_out(['Geography']))
encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [202]:
label_gender = label_encoder_gender.transform(input_data_df[['Gender']])
label_gender_df['Gender'] = pd.DataFrame(label_gender)
label_gender_df

c:\Users\adity\Desktop\Deep learning project ANN\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

   0  Gender
0  1       1

In [203]:
input_data_df=input_data_df.drop(columns = ['Geography','Gender'])
input_data_df = pd.concat(
    [
    encoded_df,input_data_df,label_gender_df],axis=1
)
input_data_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,0,Gender
0,0.0,1.0,0.0,742,35,6,125430.75,2,1,1,87342.56,1,1

In [204]:
input_data_df = input_data_df.drop(columns=[0])

In [205]:
input_data_df = input_data_df[scaler.feature_names_in_]
input_data_df.columns.to_list()

['Geography_France',
 'Geography_Germany',
 'Geography_Spain',
 'CreditScore',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary']

In [206]:
scaled_input = scaler.transform(input_data_df)

In [209]:
prediction=model.predict(scaled_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

array([[0.02474763]], dtype=float32)

In [210]:
predict_prob = prediction[0][0]
predict_prob

np.float32(0.024747627)

In [211]:
if predict_prob > 0.5:
    print("The customer is likely churn .")
else:
    print("The customer is not likely churn .")

The customer is not likely churn .