In [62]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder

In [63]:
df = pd.read_csv('Churn_Modelling.csv')
df.head(

)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [64]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [65]:
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [66]:
OneHot_Encoder= OneHotEncoder(handle_unknown='ignore',sparse_output=False)
geo_encoded = OneHot_Encoder.fit_transform(df[['Geography']]).toarray()
geo_encoded_df =pd.DataFrame(geo_encoded,columns=OneHot_Encoder.get_feature_names_out())
geo_encoded_df

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [67]:
data = pd.concat([df.drop('Geography',axis=1),geo_encoded_df] , axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [68]:
X = data.drop('EstimatedSalary',axis=1)
y= data['EstimatedSalary']

In [69]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state=42)

In [70]:
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [71]:
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('OneHot_Encoder.pkl','wb') as file:
    pickle.dump(OneHot_Encoder,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [72]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [73]:
model = Sequential([

    Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)),  ##HL1
    Dense(32,activation='relu'),  ##HL2
    Dense(1) ##output layer 

])

c:\Users\adity\Desktop\Deep learning project ANN\myenv312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [74]:
model.compile(optimizer ='adam',loss = 'mean_absolute_error',metrics =['mae'])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
log_dir= "Regressionlogs/fit/" +datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorflow_callbacks = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [76]:
early_stopping_Callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [77]:
histroy = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_test_scaled,y_test),
    epochs =100,
    callbacks = [tensorflow_callbacks,early_stopping_Callback]

)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100371.7812 - mae: 100371.7812 - val_loss: 98485.4688 - val_mae: 98485.4688
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 99493.7188 - mae: 99493.7188 - val_loss: 96694.3594 - val_mae: 96694.3594
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 96393.2031 - mae: 96393.2031 - val_loss: 92129.0000 - val_mae: 92129.0000
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 90372.7422 - mae: 90372.7422 - val_loss: 84684.8906 - val_mae: 84684.8906
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 81788.9219 - mae: 81788.9219 - val_loss: 75340.0859 - val_mae: 75340.0859
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 71993.2500 - mae: 71993.2500 - val_loss: 66081.2891 - val_mae: 66081.2891
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 63074.0117 - mae: 63074.0117 - val_loss: 58659.8984 - val_mae: 58659.8984
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 56616.3555 - mae: 56616.3555 - val_loss: 53964.8594 - val_mae: 53964.8594
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52948.5625 - mae: 52948.5625 - val_loss: 51768.6914 - val_mae: 51768.6914
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51185.9883 - mae: 51185.9883 - val_loss: 50987.2148 - val_mae: 50987.2148
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50471.2891 - mae: 50471.2891 - val_loss: 50741.5156 - val_mae: 50741.5156
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50218.3008 - mae: 50218.3008 - val_loss: 50662.2852 - val_mae: 50662.2852
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50105.4023 - mae: 50105.4023 - val_loss: 50611.3203 - val_mae: 50611.3203
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50036.2773 - mae: 50036.2773 - val_loss: 50579.8320 - val_mae: 50579.8320
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49985.4023 - mae: 49985.4023 - val_loss: 50536.6211 - val_mae: 50536.6211
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49944.4961 - mae: 49944.4961 - val_loss: 50507.5898 - val_mae: 50507.5898
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49905.7734 - mae: 49905.7734 - val_loss: 50483.8008 - val_mae: 50483.8008
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49874.9023 - mae: 49874.9023 - val_loss: 50465.3945 - val_mae: 50465.3945
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49847.5664 - mae: 49847.5664 - val_loss: 50434.9375 - val_mae: 50434.9375
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49819.2852 - mae: 49819.2852 - val_loss: 50418.3008 - val_mae: 50418.3008
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49796.1289 - mae: 49796.1289 - val_loss: 50399.0469 - val_mae: 50399.0469
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49774.1523 - mae: 49774.1523 - val_loss: 50377.0156 - val_mae: 50377.0156
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49753.4258 - mae: 49753.4258 - val_loss: 50367.1445 - val_mae: 50367.1445
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49730.9375 - mae: 49730.9375 - val_loss: 50369.0742 - val_mae: 50369.0742
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49712.8320 - mae: 49712.8320 - val_loss: 50356.2969 - val_mae: 50356.2969
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49693.7852 - mae: 49693.7852 - val_loss: 50357.1172 - val_mae: 50357.1172
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49681.4570 - mae: 49681.4570 - val_loss: 50342.1250 - val_mae: 50342.1250
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49666.8984 - mae: 49666.8984 - val_loss: 50334.5352 - val_mae: 50334.5352
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49650.4492 - mae: 49650.4492 - val_loss: 50321.2695 - val_mae: 50321.2695
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49636.3477 - mae: 49636.3477 - val_loss: 50320.6641 - val_mae: 50320.6641
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49623.4141 - mae: 49623.4141 - val_loss: 50320.5352 - val_mae: 50320.5352
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49610.5430 - mae: 49610.5430 - val_loss: 50320.2539 - val_mae: 50320.2539
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49602.0742 - mae: 49602.0742 - val_loss: 50316.5938 - val_mae: 50316.5938
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49592.1055 - mae: 49592.1055 - val_loss: 50315.9062 - val_mae: 50315.9062
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49583.6328 - mae: 49583.6328 - val_loss: 50314.8789 - val_mae: 50314.8789
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49573.0508 - mae: 49573.0508 - val_loss: 50318.1055 - val_mae: 50318.1055
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49564.2852 - mae: 49564.2852 - val_loss: 50312.8516 - val_mae: 50312.8516
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49553.4336 - mae: 49553.4336 - val_loss: 50302.9297 - val_mae: 50302.9297
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49543.3984 - mae: 49543.3984 - val_loss: 50304.0195 - val_mae: 50304.0195
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49539.3398 - mae: 49539.3398 - val_loss: 50306.9375 - val_mae: 50306.9375
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49532.8594 - mae: 49532.8594 - val_loss: 50297.2031 - val_mae: 50297.2031
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49521.8164 - mae: 49521.8164 - val_loss: 50304.3633 - val_mae: 50304.3633
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49514.6172 - mae: 49514.6172 - val_loss: 50300.9414 - val_mae: 50300.9414
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49507.4336 - mae: 49507.4336 - val_loss: 50304.3164 - val_mae: 50304.3164
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49502.1680 - mae: 49502.1680 - val_loss: 50299.2617 - val_mae: 50299.2617
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49494.4570 - mae: 49494.4570 - val_loss: 50305.0586 - val_mae: 50305.0586
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49486.5273 - mae: 49486.5273 - val_loss: 50298.9219 - val_mae: 50298.9219
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49478.7109 - mae: 49478.7109 - val_loss: 50302.9102 - val_mae: 50302.9102
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49477.1094 - mae: 49477.1094 - val_loss: 50302.7461 - val_mae: 50302.7461
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49466.9414 - mae: 49466.9414 - val_loss: 50293.7422 - val_mae: 50293.7422
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49460.4531 - mae: 49460.4531 - val_loss: 50296.3359 - val_mae: 50296.3359
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49460.1250 - mae: 49460.1250 - val_loss: 50298.9844 - val_mae: 50298.9844
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49450.3398 - mae: 49450.3398 - val_loss: 50295.0391 - val_mae: 50295.0391
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49444.3945 - mae: 49444.3945 - val_loss: 50297.6953 - val_mae: 50297.6953
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49436.6328 - mae: 49436.6328 - val_loss: 50295.4648 - val_mae: 50295.4648
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49434.3555 - mae: 49434.3555 - val_loss: 50305.1406 - val_mae: 50305.1406
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49429.8711 - mae: 49429.8711 - val_loss: 50305.9570 - val_mae: 50305.9570
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49423.5859 - mae: 49423.5859 - val_loss: 50302.3398 - val_mae: 50302.3398
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49417.7617 - mae: 49417.7617 - val_loss: 50300.9492 - val_mae: 50300.9492
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49413.1094 - mae: 49413.1094 - val_loss: 50285.6211 - val_mae: 50285.6211
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49408.7891 - mae: 49408.7891 - val_loss: 50282.6797 - val_mae: 50282.6797
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49402.4375 - mae: 49402.4375 - val_loss: 50287.1133 - val_mae: 50287.1133
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49398.9805 - mae: 49398.9805 - val_loss: 50295.1133 - val_mae: 50295.1133
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49393.9102 - mae: 49393.9102 - val_loss: 50289.9727 - val_mae: 50289.9727
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49389.2734 - mae: 49389.2734 - val_loss: 50304.1172 - val_mae: 50304.1172
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49385.5898 - mae: 49385.5898 - val_loss: 50291.0117 - val_mae: 50291.0117
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49381.0312 - mae: 49381.0312 - val_loss: 50298.1016 - val_mae: 50298.1016
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49377.3164 - mae: 49377.3164 - val_loss: 50308.1172 - val_mae: 50308.1172
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49372.5469 - mae: 49372.5469 - val_loss: 50295.7930 - val_mae: 50295.7930
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49370.3320 - mae: 49370.3320 - val_loss: 50306.6172 - val_mae: 50306.6172
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49362.3633 - mae: 49362.3633 - val_loss: 50287.6719 - val_mae: 50287.6719

In [78]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [79]:
%tensorboard --logdir Regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 11940), started 0:23:49 ago. (Use '!kill 11940' to kill it.)

In [80]:
test_loss ,test_mae = model.evaluate(X_test_scaled,y_test)

print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - loss: 50282.6797 - mae: 50282.6797
Test MAE : 50282.6796875

In [81]:
model.save("RegressionModel.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.